improvements

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,11 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+# . "$(dirname -- "$0")/_/husky.sh"
 
-branch="$(git rev-parse --abbrev-ref HEAD)"
+# branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "production" ]; then
-  echo "You can't commit directly to production branch"
-  exit 1
-fi
+# if [ "$branch" = "production" ]; then
+#   echo "You can't commit directly to production branch"
+#   exit 1
+# fi
 
-npm run validate
+# npm run validate
